# Generated by Django 3.0.5 on 2020-07-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledgeform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='pledge',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=100),
        ),
    ]
